apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-dp

spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - image: daruken/gateway:56cd288b235e39f1ee000b7a8fcfe166d50f9a4f
          name: gateway
          ports:
            - containerPort: 28080

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
spec:
  ports:
    - name: svc-port
      port: 28080
      targetPort: 28080
  selector:
    app: gateway
    type: NodePort
