apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
spec:
  type: NodePort
  ports:
    - nodePort: 30008
      port: 28080
      targetPort: 28080
      protocol: TCP
  selector:
    app: gateway
