apiVersion: apps/v1
kind: Deployment
metadata:
  name: kingen-dp

spec:
  selector:
    matchLabels:
      app: kingen
  template:
    metadata:
      labels:
        app: kingen
    spec:
      containers:
        - name: kingen
          image: daruken/kingen:56cd288b235e39f1ee000b7a8fcfe166d50f9a4f
          ports:
            - containerPort: 8761
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
