apiVersion: v1
kind: Service
metadata:
  name: kingen-svc
spec:
  type: NodePort
  ports:
    - nodePort: 30007
      port: 8761
      targetPort: 8761
      protocol: TCP
  selector:
    app: kingen
