apiVersion: apps/v1
kind: Deployment
metadata:
  name: kingen-dp

spec:
  selector:
    matchLabels:
      app: kingen
  template:
    metadata:
      labels:
        app: kingen
    spec:
      containers:
        - image: daruken/kingen
          name: kingen
          ports:
            - containerPort: 8761

---
apiVersion: v1
kind: Service
metadata:
  name: kingen-svc
spec:
  ports:
    - port: 8761
      targetPort: 8761
  selector:
    app: kingen
