apiVersion: apps/v1
kind: Deployment
metadata:
  name: kingen-dp

spec:
  selector:
    matchLabels:
      app: kingen
  template:
    metadata:
      labels:
        app: kingen
    spec:
      containers:
        - image: daruken/kingen:56cd288b235e39f1ee000b7a8fcfe166d50f9a4f
          name: kingen
          ports:
            - containerPort: 8761

---
apiVersion: v1
kind: Service
metadata:
  name: kingen-svc
spec:
  ports:
    - name: svc-port
      port: 8761
      targetPort: 8761
  selector:
    app: kingen
    externalTrafficPolicy: Local
    type: LoadBalancer
